'use client';

import { createContext, useContext, useState, useEffect, useCallback } from 'react';

// Traductions
const translations = {
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.bookings': 'Mes commandes',
    'nav.profile': 'Mon profil',
    'nav.login': 'Connexion',
    'nav.logout': 'Déconnexion',
    'nav.register': 'Inscription',
    'nav.addresses': 'Mes adresses',
    'nav.providerSpace': 'Espace prestataire',
    'nav.becomeProvider': 'Devenir prestataire',
    'nav.howItWorks': 'Comment ça marche',
    'nav.iAmClient': 'Je suis Client',
    'nav.iAmProvider': 'Je suis Prestataire',
    'nav.bookService': 'Réserver un service à domicile',
    'nav.offerServices': 'Proposer mes services',
    'nav.menu': 'Menu',
    'nav.completeProfile': 'Complétez votre profil',
    'nav.completeProfileDesc': 'Finalisez votre inscription pour accéder à toutes les fonctionnalités',
    'nav.completeNow': 'Compléter maintenant',

    // Page d'accueil
    'home.title': 'Services à domicile à Marrakech',
    'home.subtitle': 'Beauté, ménage, réparations... Tout ce dont vous avez besoin, à portée de main',
    'home.search': 'Rechercher un service...',
    'home.categories': 'Catégories populaires',
    'home.categoriesSubtitle': 'Découvrez nos services les plus demandés',
    'home.popular': 'Services populaires',
    'home.popularSubtitle': 'Les services les plus réservés par nos clients',
    'home.nearYou': 'Près de vous',
    'home.viewAllCategories': 'Voir toutes les catégories',
    'home.viewAllServices': 'Voir tous les services',
    'home.howItWorks': 'Comment ça marche ?',
    'home.howItWorksSubtitle': 'Réservez vos services en 4 étapes simples',
    'home.step1Title': 'Recherchez',
    'home.step1Desc': 'Parcourez notre catalogue de services et choisissez celui qui vous convient.',
    'home.step2Title': 'Réservez',
    'home.step2Desc': 'Sélectionnez une date et une heure qui vous arrangent.',
    'home.step3Title': 'Payez',
    'home.step3Desc': 'Payez en toute sécurité en ligne ou en espèces.',
    'home.step4Title': 'Profitez',
    'home.step4Desc': 'Un professionnel qualifié vient chez vous à l\'heure prévue.',
    'home.readyToStart': 'Prêt à commencer ?',
    'home.signUpNow': 'Inscrivez-vous maintenant et profitez de services de qualité à domicile',
    'home.createAccount': 'Créer un compte',
    'home.noCategories': 'Aucune catégorie disponible pour le moment',
    'home.noServices': 'Aucun service disponible pour le moment',

    // Booking
    'booking.title': 'Réserver un service',
    'booking.selectProvider': 'Choisir un prestataire',
    'booking.nearbyProviders': 'Prestataires à proximité',
    'booking.noProviders': 'Aucun prestataire disponible',
    'booking.selectDate': 'Choisir la date',
    'booking.selectTime': 'Choisir l\'heure',
    'booking.selectAddress': 'Adresse de prestation',
    'booking.confirm': 'Confirmer la réservation',
    'booking.total': 'Total',
    'booking.basePrice': 'Prix de base',
    'booking.distanceFee': 'Frais de déplacement',
    'booking.noDistanceFee': 'Pas de frais de déplacement',
    'booking.formula': 'Formule',
    'booking.standard': 'Standard',
    'booking.express': 'Express',
    'booking.premium': 'Premium',

    // Provider Card
    'provider.nearest': 'LE PLUS PROCHE',
    'provider.available': 'Disponible maintenant',
    'provider.availableFrom': 'Disponible à partir de',
    'provider.unavailable': 'Indisponible',
    'provider.distance': 'À {distance} de vous',
    'provider.reviews': 'avis',
    'provider.select': 'Choisir ce prestataire',
    'provider.selected': 'Sélectionné',
    'provider.priceDetails': 'Détails',
    'provider.hideDetails': 'Masquer',
    'provider.totalPrice': 'Prix total',
    'provider.estimatedDuration': 'Durée estimée',

    // Chat
    'chat.title': 'Chat avec le prestataire',
    'chat.titleClient': 'Chat avec le client',
    'chat.placeholder': 'Écrivez votre message...',
    'chat.send': 'Envoyer',
    'chat.noMessages': 'Aucun message. Commencez la conversation !',
    'chat.secureNote': 'Communication sécurisée GlamGo',
    'chat.translations': 'Traductions',
    'chat.imageWarning': 'Photos compromettantes interdites',
    'chat.contactWarning': 'Numéros, emails et réseaux sociaux interdits',

    // Commandes
    'orders.title': 'Mes réservations',
    'orders.pending': 'En attente',
    'orders.accepted': 'Acceptée',
    'orders.inProgress': 'En cours',
    'orders.completed': 'Terminée',
    'orders.cancelled': 'Annulée',
    'orders.noOrders': 'Aucune réservation',
    'orders.viewDetails': 'Voir les détails',
    'orders.trackProvider': 'Suivre le prestataire',

    // Formulaires
    'form.email': 'Email',
    'form.password': 'Mot de passe',
    'form.confirmPassword': 'Confirmer le mot de passe',
    'form.firstName': 'Prénom',
    'form.lastName': 'Nom',
    'form.phone': 'Téléphone',
    'form.address': 'Adresse',
    'form.city': 'Ville',
    'form.submit': 'Envoyer',
    'form.cancel': 'Annuler',
    'form.save': 'Enregistrer',
    'form.required': 'Champ obligatoire',

    // Messages
    'message.success': 'Succès',
    'message.error': 'Erreur',
    'message.loading': 'Chargement...',
    'message.confirmAction': 'Êtes-vous sûr ?',
    'message.yes': 'Oui',
    'message.no': 'Non',

    // Paiement
    'payment.title': 'Paiement',
    'payment.method': 'Mode de paiement',
    'payment.cash': 'Espèces',
    'payment.card': 'Carte bancaire',
    'payment.pay': 'Payer',

    // Langue
    'language.switch': 'العربية',
    'language.current': 'Français',

    // ProviderCard
    'provider.noDistanceFee': 'Pas de frais de déplacement',
    'provider.distanceFeeAmount': '+{fee} {currency} de frais de déplacement',
    'provider.seeDetails': 'Voir détails',
    'provider.interventionRadius': 'Rayon d\'intervention : {radius} km',
    'provider.extraDistance': 'Distance supplémentaire : {distance} km',
    'provider.rate': 'Tarif : {rate} {currency}/km',
    'provider.estimatedDurationMin': 'Durée estimée: {duration} min',
    'provider.defaultName': 'Prestataire',
    'provider.totalPrice': 'Prix total',
    'provider.hideDetails': 'Masquer',
    'provider.priceDetails': 'Détails',
    'provider.selected': 'Sélectionné',
    'provider.select': 'Choisir ce prestataire',

    // Chat
    'chat.title': 'Chat avec le prestataire',
    'chat.titleClient': 'Chat avec le client',
    'chat.secureNote': 'Communication sécurisée GlamGo',
    'chat.translations': 'Traductions',
    'chat.noMessages': 'Aucun message. Commencez la conversation !',
    'chat.send': 'Envoyer',
    'chat.loadingConversation': 'Chargement de la conversation...',
    'chat.chatDisabled': 'Le chat est désactivé pour cette commande',
    'chat.analyzingImage': 'Analyse de l\'image en cours...',
    'chat.contentBlocked': 'Contenu bloqué',
    'chat.confirmRequired': 'Confirmation obligatoire',
    'chat.strictlyForbidden': 'STRICTEMENT INTERDIT :',
    'chat.intimatePhotos': 'Photos intimes ou à caractère sexuel',
    'chat.nudityPhotos': 'Photos de nudité (partielle ou totale)',
    'chat.compromisePhotos': 'Photos compromettantes',
    'chat.idPhotos': 'Photos de documents d\'identité',
    'chat.allowed': 'AUTORISÉ :',
    'chat.workPhotos': 'Photos du travail effectué',
    'chat.equipmentPhotos': 'Photos de matériel professionnel',
    'chat.violationWarning': 'Toute violation entraînera :',
    'chat.accountSuspension': 'Suspension immédiate du compte',
    'chat.authoritiesReport': 'Signalement aux autorités compétentes',
    'chat.legalAction': 'Poursuites judiciaires possibles',
    'chat.certifyImage': 'Je certifie que cette image ne contient aucun contenu inapproprié, intime ou compromettant.',
    'chat.sendImage': 'Envoyer l\'image',
    'chat.securityWarning': 'Photos compromettantes interdites | Numéros, emails et réseaux sociaux interdits',
    'chat.uploadImage': 'Envoyer une image',
    'chat.writePlaceholder': 'Écrivez votre message... (Français ou العربية)',
    'chat.read': 'Lu',
    'chat.sent': 'Envoyé',
    'chat.errorSending': 'Erreur lors de l\'envoi',

    // Quick messages - Provider
    'chat.quick.onMyWay': 'Je suis en route',
    'chat.quick.arrive5min': 'J\'arrive dans 5 minutes',
    'chat.quick.arrived': 'Je suis arrivé',
    'chat.quick.starting': 'Je commence',
    'chat.quick.serviceComplete': 'Service terminé',
    // Quick messages - Client
    'chat.quick.ok': 'D\'accord',
    'chat.quick.thanks': 'Merci',
    'chat.quick.whereAreYou': 'Où êtes-vous ?',
    'chat.quick.waiting': 'Je vous attends',
    'chat.quick.perfect': 'Parfait',

    // Review Modal
    'review.title': 'Évaluez votre expérience',
    'review.provider': 'Prestataire',
    'review.service': 'Service',
    'review.globalRating': 'Note globale',
    'review.clickToRate': 'Cliquez pour noter',
    'review.veryUnsatisfied': 'Très insatisfait',
    'review.unsatisfied': 'Insatisfait',
    'review.correct': 'Correct',
    'review.satisfied': 'Satisfait',
    'review.excellent': 'Excellent !',
    'review.detailedRatings': 'Notes détaillées (optionnel)',
    'review.serviceQuality': 'Qualité du service',
    'review.punctuality': 'Ponctualité',
    'review.professionalism': 'Professionnalisme',
    'review.commentLabel': 'Votre commentaire (optionnel)',
    'review.commentPlaceholder': 'Partagez votre expérience avec ce prestataire...',
    'review.submit': 'Envoyer mon avis',
    'review.submitting': 'Envoi...',
    'review.pleaseRate': 'Veuillez donner une note globale',
    'review.errorSending': 'Erreur lors de l\'envoi de l\'avis',

    // Formula Selector
    'formula.title': 'Choisir votre formule',
    'formula.subtitle': 'Sélectionnez le type de service qui vous convient',
    'formula.learnMore': 'En savoir plus',
    'formula.loading': 'Chargement des formules...',
    'formula.standard': 'Standard',
    'formula.recurring': 'Récurrent',
    'formula.premium': 'Premium',
    'formula.urgent': 'Urgence',
    'formula.night': 'Nuit',
    'formula.recommendedForTime': 'Recommandé pour cette heure',
    'formula.suitedForUrgency': 'Adapté à votre urgence',
    'formula.specialRules': 'Ce service a des règles spécifiques',

    // Login Page
    'login.title': 'Connexion Client',
    'login.subtitle': 'Accédez à votre compte GlamGo et réservez vos services',
    'login.backToHome': 'Retour à l\'accueil',
    'login.emailRequired': 'L\'email est requis',
    'login.emailInvalid': 'L\'email n\'est pas valide',
    'login.passwordRequired': 'Le mot de passe est requis',
    'login.wrongCredentials': 'Email ou mot de passe incorrect',
    'login.forgotPassword': 'Mot de passe oublié ?',
    'login.rememberMe': 'Se souvenir de moi',
    'login.connecting': 'Connexion en cours...',
    'login.connect': 'Se connecter',
    'login.noAccount': 'Vous n\'avez pas de compte ?',
    'login.signUp': 'Inscrivez-vous',
    'login.areProvider': 'Vous êtes prestataire ?',
    'login.providerLogin': 'Connexion prestataire',
    'login.showPassword': 'Afficher le mot de passe',
    'login.hidePassword': 'Masquer le mot de passe',

    // Register Page
    'register.personalInfo': 'Informations personnelles',
    'register.yourAddress': 'Votre adresse',
    'register.paymentMethod': 'Moyen de paiement',
    'register.yourPreferences': 'Vos préférences',
    'register.createAccount': 'Créez votre compte GlamGo',
    'register.whereService': 'Où souhaitez-vous recevoir vos prestations ?',
    'register.registerCard': 'Enregistrez votre carte bancaire',
    'register.customizeExperience': 'Personnalisez votre expérience (optionnel)',
    'register.stepInfo': 'Infos',
    'register.stepAddress': 'Adresse',
    'register.stepPayment': 'Paiement',
    'register.stepPreferences': 'Préférences',
    'register.firstNameRequired': 'Le prénom est requis',
    'register.lastNameRequired': 'Le nom est requis',
    'register.phoneRequired': 'Le téléphone est requis',
    'register.phoneInvalid': 'Le numéro doit commencer par 06 ou 07 et contenir 10 chiffres',
    'register.birthDateRequired': 'La date de naissance est requise',
    'register.mustBe18': 'Vous devez avoir au moins 18 ans pour vous inscrire',
    'register.passwordMinLength': 'Le mot de passe doit contenir au moins 6 caractères',
    'register.confirmPasswordRequired': 'Veuillez confirmer votre mot de passe',
    'register.passwordsDontMatch': 'Les mots de passe ne correspondent pas',
    'register.acceptTerms': 'Vous devez accepter les conditions pour continuer',
    'register.addressRequired': 'L\'adresse est requise',
    'register.selectAddressWithGeo': 'Veuillez sélectionner une adresse avec géolocalisation',
    'register.cityRequired': 'La ville est requise',
    'register.yourFirstName': 'Votre prénom',
    'register.yourLastName': 'Votre nom',
    'register.minimum6Chars': 'Minimum 6 caractères',
    'register.retypePassword': 'Retapez votre mot de passe',
    'register.iAccept': 'J\'accepte les',
    'register.termsAndConditions': 'conditions générales',
    'register.and': 'et la',
    'register.privacyPolicy': 'politique de confidentialité',
    'register.continue': 'Continuer',
    'register.back': 'Retour',
    'register.registering': 'Inscription...',
    'register.successRegistration': 'Inscription réussie ! Configurons votre moyen de paiement.',
    'register.connectionError': 'Erreur lors de la connexion. Veuillez vous connecter manuellement.',
    'register.cardSaved': 'Carte enregistrée ! Dernière étape...',
    'register.selectServices': 'Sélectionnez les services qui vous intéressent pour personnaliser votre expérience.',
    'register.skip': 'Passer',
    'register.finalizing': 'Finalisation...',
    'register.finish': 'Terminer',
    'register.haveAccount': 'Vous avez déjà un compte ?',
    'register.logIn': 'Connectez-vous',
    'register.completeAddress': 'Adresse complète',
    'register.startTypingAddress': 'Commencez à taper votre adresse...',
    'register.selectSuggestedAddress': 'Sélectionnez une adresse suggérée pour une localisation précise',
    'register.selectCity': 'Sélectionnez votre ville',
    'register.paymentInfo': 'Vous pourrez également payer en espèces lors de la prestation. La carte bancaire sert de garantie pour vos réservations.',

    // Profile Page
    'profile.title': 'Mon Profil',
    'profile.subtitle': 'Gérez vos informations personnelles',
    'profile.loading': 'Chargement...',
    'profile.profilePhoto': 'Photo de profil',
    'profile.change': 'Changer',
    'profile.user': 'Utilisateur',
    'profile.clientGlamgo': 'Client GlamGo',
    'profile.modify': 'Modifier',
    'profile.firstName': 'Prénom',
    'profile.lastName': 'Nom',
    'profile.emailAddress': 'Adresse e-mail',
    'profile.phone': 'Téléphone',
    'profile.birthDate': 'Date de naissance',
    'profile.city': 'Ville',
    'profile.selectCity': 'Sélectionnez une ville',
    'profile.address': 'Adresse',
    'profile.typeAddress': 'Tapez votre adresse (ex: Maarif, Guéliz...)',
    'profile.saving': 'Enregistrement...',
    'profile.save': 'Enregistrer',
    'profile.updateSuccess': 'Profil mis à jour avec succès !',
    'profile.updateError': 'Erreur lors de la mise à jour du profil',
    'profile.imageTooBig': 'L\'image ne doit pas dépasser 5 Mo',
    'profile.fileMustBeImage': 'Le fichier doit être une image',
    'profile.uploadError': 'Erreur lors de l\'upload de l\'image',
    'profile.statistics': 'Statistiques',
    'profile.memberSince': 'Membre depuis {date}',
    'profile.security': 'Sécurité',
    'profile.accountSecured': 'Votre compte est sécurisé',
    'profile.loyalty': 'Fidélité',
    'profile.premiumServices': 'Profitez de nos services premium',

    // Cards
    'card.servicesAvailable': '{count} services disponibles',
    'card.perService': '/ service',
    'card.from': 'À partir de',
    'card.bookNow': 'Réserver',

    // Price Breakdown
    'price.calculating': 'Calcul du prix...',
    'price.calculationError': 'Erreur de calcul',
    'price.connectionError': 'Erreur de connexion',
    'price.basePrice': 'Prix de base',
    'price.distanceFee': 'Frais de déplacement',
    'price.noDistanceFee': 'Pas de frais de déplacement',
    'price.nightSupplement': 'Supplément nuit',
    'price.nights': 'nuits',
    'price.consecutiveNights': 'nuits consécutives',
    'price.total': 'Total',
    'price.details': 'Détail du prix',
    'price.formula': 'Formule',
    'price.duration': 'Durée',
    'price.quantity': 'Quantité',
    'price.totalDistance': 'Distance totale',
    'price.freeRadius': 'Rayon gratuit',
    'price.excessDistance': 'Distance excédentaire',
    'price.rate': 'Tarif',
    'price.travel': 'Déplacement',
    'price.included': 'Inclus',
    'price.subtotal': 'Sous-total',
    'price.commission': 'Commission GlamGo',
    'price.totalToPay': 'Total à payer',
    'price.providerEarnings': 'Revenu prestataire',
    'price.nightService': 'Service de nuit (22h - 6h)',

    // Distance Fee Modal
    'distance.title': 'Frais de déplacement',
    'distance.howCalculated': 'Comment sont calculés les frais pour {name}',
    'distance.footerNote': 'Les frais de déplacement permettent au prestataire de couvrir ses déplacements au-delà de son rayon d\'intervention habituel.',
    'distance.understood': 'J\'ai compris',
    'distance.provider': 'Prestataire',
    'distance.radius': 'Rayon',
    'distance.yourPosition': 'Votre position',
    'distance.distanceLabel': 'Distance',
    'distance.totalDistance': 'Distance totale',
    'distance.freeRadius': 'Rayon d\'intervention gratuit',
    'distance.excessDistance': 'Distance excédentaire',
    'distance.none': 'Aucune',
    'distance.free': 'Gratuit',
    'distance.noFee': 'Pas de frais de déplacement',
    'distance.feeAmount': '+{amount} {currency} de frais de déplacement',
    'distance.freeZone': 'Zone d\'intervention gratuite',
    'distance.inRadius': 'Vous êtes à {distance} km du prestataire, dans son rayon d\'intervention de {radius} km.',
    'distance.outOfRadius': 'Vous êtes à {distance} km du prestataire, au-delà de son rayon d\'intervention de {radius} km.',
    'distance.calculationDetail': 'Détail du calcul',
    'distance.inRadiusInfo': 'Ce prestataire intervient dans votre zone sans frais supplémentaires.',
    'distance.outOfRadiusInfo': 'Ces frais permettent au prestataire de couvrir ses déplacements supplémentaires pour venir jusqu\'à vous.',
    'distance.noFeeInZone': 'Pas de frais de déplacement - Vous êtes dans la zone d\'intervention',
    'distance.alertExplanation': 'Ce prestataire intervient gratuitement jusqu\'à {radius} km. Votre adresse est à {distance} km.',
    'distance.additionalDistance': 'Distance supplémentaire',
    'distance.rate': 'Tarif',

    // Services Page
    'services.loading': 'Chargement des services...',
    'services.allServices': 'Tous nos services',
    'services.subtitle': 'Découvrez notre large gamme de services à domicile à Marrakech',
    'services.discoverFormulas': 'Découvrir nos formules de tarification',
    'services.noServices': 'Aucun service disponible',
    'services.filterByCategory': 'Filtrer par catégorie',
    'services.allCategories': 'Tous les services',
    'services.searchPlaceholder': 'Rechercher un service...',
    'services.radius': 'Rayon',
    'services.noResults': 'Aucun service trouvé',
    'services.noResultsHint': 'Essayez de modifier vos critères de recherche',
    'services.resultsCount': '{count} service(s) trouvé(s)',

    // Common
    'common.required': 'obligatoire',
    'common.optional': 'optionnel',
    'common.cancel': 'Annuler',
    'common.error': 'Erreur',
    'common.close': 'Fermer',
    'common.reviews': 'avis',
    'common.loading': 'Chargement...',
  },

  ar: {
    // Navigation
    'nav.home': 'الرئيسية',
    'nav.services': 'الخدمات',
    'nav.bookings': 'طلباتي',
    'nav.profile': 'ملفي الشخصي',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    'nav.register': 'إنشاء حساب',
    'nav.addresses': 'عناويني',
    'nav.providerSpace': 'فضاء مقدم الخدمة',
    'nav.becomeProvider': 'كن مقدم خدمة',
    'nav.howItWorks': 'كيف يعمل',
    'nav.iAmClient': 'أنا عميل',
    'nav.iAmProvider': 'أنا مقدم خدمة',
    'nav.bookService': 'حجز خدمة منزلية',
    'nav.offerServices': 'تقديم خدماتي',
    'nav.menu': 'القائمة',
    'nav.completeProfile': 'أكمل ملفك الشخصي',
    'nav.completeProfileDesc': 'أكمل تسجيلك للوصول إلى جميع الميزات',
    'nav.completeNow': 'أكمل الآن',

    // Page d'accueil
    'home.title': 'خدمات منزلية في مراكش',
    'home.subtitle': 'تجميل، تنظيف، إصلاحات... كل ما تحتاجه في متناول يدك',
    'home.search': 'ابحث عن خدمة...',
    'home.categories': 'الفئات الشائعة',
    'home.categoriesSubtitle': 'اكتشف خدماتنا الأكثر طلباً',
    'home.popular': 'الخدمات الشائعة',
    'home.popularSubtitle': 'الخدمات الأكثر حجزاً من عملائنا',
    'home.nearYou': 'بالقرب منك',
    'home.viewAllCategories': 'عرض جميع الفئات',
    'home.viewAllServices': 'عرض جميع الخدمات',
    'home.howItWorks': 'كيف يعمل؟',
    'home.howItWorksSubtitle': 'احجز خدماتك في 4 خطوات بسيطة',
    'home.step1Title': 'ابحث',
    'home.step1Desc': 'تصفح كتالوج خدماتنا واختر ما يناسبك.',
    'home.step2Title': 'احجز',
    'home.step2Desc': 'اختر التاريخ والوقت المناسبين لك.',
    'home.step3Title': 'ادفع',
    'home.step3Desc': 'ادفع بأمان عبر الإنترنت أو نقداً.',
    'home.step4Title': 'استمتع',
    'home.step4Desc': 'محترف مؤهل يأتي إلى منزلك في الوقت المحدد.',
    'home.readyToStart': 'مستعد للبدء؟',
    'home.signUpNow': 'سجل الآن واستمتع بخدمات عالية الجودة في منزلك',
    'home.createAccount': 'إنشاء حساب',
    'home.noCategories': 'لا توجد فئات متاحة حالياً',
    'home.noServices': 'لا توجد خدمات متاحة حالياً',

    // Booking
    'booking.title': 'حجز خدمة',
    'booking.selectProvider': 'اختر مقدم الخدمة',
    'booking.nearbyProviders': 'مقدمو الخدمات القريبون',
    'booking.noProviders': 'لا يوجد مقدمو خدمات متاحون',
    'booking.selectDate': 'اختر التاريخ',
    'booking.selectTime': 'اختر الوقت',
    'booking.selectAddress': 'عنوان الخدمة',
    'booking.confirm': 'تأكيد الحجز',
    'booking.total': 'المجموع',
    'booking.basePrice': 'السعر الأساسي',
    'booking.distanceFee': 'رسوم التنقل',
    'booking.noDistanceFee': 'بدون رسوم تنقل',
    'booking.formula': 'الصيغة',
    'booking.standard': 'عادي',
    'booking.express': 'سريع',
    'booking.premium': 'مميز',

    // Provider Card
    'provider.nearest': 'الأقرب',
    'provider.available': 'متاح الآن',
    'provider.availableFrom': 'متاح من',
    'provider.unavailable': 'غير متاح',
    'provider.distance': 'على بعد {distance} منك',
    'provider.reviews': 'تقييمات',
    'provider.select': 'اختر هذا المقدم',
    'provider.selected': 'تم الاختيار',
    'provider.priceDetails': 'التفاصيل',
    'provider.hideDetails': 'إخفاء',
    'provider.totalPrice': 'السعر الإجمالي',
    'provider.estimatedDuration': 'المدة المقدرة',

    // Chat
    'chat.title': 'محادثة مع المقدم',
    'chat.titleClient': 'محادثة مع العميل',
    'chat.placeholder': 'اكتب رسالتك...',
    'chat.send': 'إرسال',
    'chat.noMessages': 'لا توجد رسائل. ابدأ المحادثة!',
    'chat.secureNote': 'اتصال آمن من GlamGo',
    'chat.translations': 'الترجمات',
    'chat.imageWarning': 'الصور المخلة ممنوعة',
    'chat.contactWarning': 'أرقام الهواتف والبريد الإلكتروني ممنوعة',

    // Commandes
    'orders.title': 'حجوزاتي',
    'orders.pending': 'قيد الانتظار',
    'orders.accepted': 'مقبول',
    'orders.inProgress': 'جاري التنفيذ',
    'orders.completed': 'مكتمل',
    'orders.cancelled': 'ملغي',
    'orders.noOrders': 'لا توجد حجوزات',
    'orders.viewDetails': 'عرض التفاصيل',
    'orders.trackProvider': 'تتبع المقدم',

    // Formulaires
    'form.email': 'البريد الإلكتروني',
    'form.password': 'كلمة المرور',
    'form.confirmPassword': 'تأكيد كلمة المرور',
    'form.firstName': 'الاسم الأول',
    'form.lastName': 'اسم العائلة',
    'form.phone': 'الهاتف',
    'form.address': 'العنوان',
    'form.city': 'المدينة',
    'form.submit': 'إرسال',
    'form.cancel': 'إلغاء',
    'form.save': 'حفظ',
    'form.required': 'حقل مطلوب',

    // Messages
    'message.success': 'نجاح',
    'message.error': 'خطأ',
    'message.loading': 'جاري التحميل...',
    'message.confirmAction': 'هل أنت متأكد؟',
    'message.yes': 'نعم',
    'message.no': 'لا',

    // Paiement
    'payment.title': 'الدفع',
    'payment.method': 'طريقة الدفع',
    'payment.cash': 'نقدي',
    'payment.card': 'بطاقة بنكية',
    'payment.pay': 'ادفع',

    // Langue
    'language.switch': 'Français',
    'language.current': 'العربية',

    // ProviderCard
    'provider.noDistanceFee': 'بدون رسوم تنقل',
    'provider.distanceFeeAmount': '+{fee} {currency} رسوم التنقل',
    'provider.seeDetails': 'عرض التفاصيل',
    'provider.interventionRadius': 'نطاق التدخل: {radius} كم',
    'provider.extraDistance': 'المسافة الإضافية: {distance} كم',
    'provider.rate': 'التعريفة: {rate} {currency}/كم',
    'provider.estimatedDurationMin': 'المدة المقدرة: {duration} دقيقة',
    'provider.defaultName': 'مقدم الخدمة',
    'provider.totalPrice': 'السعر الإجمالي',
    'provider.hideDetails': 'إخفاء',
    'provider.priceDetails': 'التفاصيل',
    'provider.selected': 'تم الاختيار',
    'provider.select': 'اختر مقدم الخدمة هذا',

    // Chat
    'chat.title': 'محادثة مع مقدم الخدمة',
    'chat.titleClient': 'محادثة مع العميل',
    'chat.secureNote': 'اتصال آمن من GlamGo',
    'chat.translations': 'ترجمات',
    'chat.noMessages': 'لا توجد رسائل. ابدأ المحادثة!',
    'chat.send': 'إرسال',
    'chat.loadingConversation': 'جاري تحميل المحادثة...',
    'chat.chatDisabled': 'الدردشة معطلة لهذا الطلب',
    'chat.analyzingImage': 'جاري تحليل الصورة...',
    'chat.contentBlocked': 'محتوى محظور',
    'chat.confirmRequired': 'التأكيد مطلوب',
    'chat.strictlyForbidden': 'ممنوع منعاً باتاً:',
    'chat.intimatePhotos': 'صور حميمة أو ذات طابع جنسي',
    'chat.nudityPhotos': 'صور عري (جزئي أو كلي)',
    'chat.compromisePhotos': 'صور مخلة',
    'chat.idPhotos': 'صور وثائق الهوية',
    'chat.allowed': 'مسموح:',
    'chat.workPhotos': 'صور العمل المنجز',
    'chat.equipmentPhotos': 'صور المعدات المهنية',
    'chat.violationWarning': 'أي مخالفة ستؤدي إلى:',
    'chat.accountSuspension': 'تعليق الحساب فوراً',
    'chat.authoritiesReport': 'الإبلاغ للسلطات المختصة',
    'chat.legalAction': 'إجراءات قانونية محتملة',
    'chat.certifyImage': 'أؤكد أن هذه الصورة لا تحتوي على أي محتوى غير لائق أو حميم أو مخل.',
    'chat.sendImage': 'إرسال الصورة',
    'chat.securityWarning': 'الصور المخلة ممنوعة | الأرقام والبريد الإلكتروني ممنوعة',
    'chat.uploadImage': 'إرسال صورة',
    'chat.writePlaceholder': 'اكتب رسالتك... (Français أو العربية)',
    'chat.read': 'مقروء',
    'chat.sent': 'مُرسل',
    'chat.errorSending': 'خطأ في الإرسال',

    // Quick messages - Provider
    'chat.quick.onMyWay': 'أنا في الطريق',
    'chat.quick.arrive5min': 'سأصل خلال 5 دقائق',
    'chat.quick.arrived': 'وصلت',
    'chat.quick.starting': 'أبدأ الآن',
    'chat.quick.serviceComplete': 'انتهت الخدمة',
    // Quick messages - Client
    'chat.quick.ok': 'حسناً',
    'chat.quick.thanks': 'شكراً',
    'chat.quick.whereAreYou': 'أين أنت؟',
    'chat.quick.waiting': 'أنتظرك',
    'chat.quick.perfect': 'ممتاز',

    // Review Modal
    'review.title': 'قيّم تجربتك',
    'review.provider': 'مقدم الخدمة',
    'review.service': 'الخدمة',
    'review.globalRating': 'التقييم العام',
    'review.clickToRate': 'انقر للتقييم',
    'review.veryUnsatisfied': 'غير راضٍ جداً',
    'review.unsatisfied': 'غير راضٍ',
    'review.correct': 'مقبول',
    'review.satisfied': 'راضٍ',
    'review.excellent': 'ممتاز!',
    'review.detailedRatings': 'تقييمات تفصيلية (اختياري)',
    'review.serviceQuality': 'جودة الخدمة',
    'review.punctuality': 'الالتزام بالموعد',
    'review.professionalism': 'الاحترافية',
    'review.commentLabel': 'تعليقك (اختياري)',
    'review.commentPlaceholder': 'شارك تجربتك مع مقدم الخدمة هذا...',
    'review.submit': 'إرسال تقييمي',
    'review.submitting': 'جاري الإرسال...',
    'review.pleaseRate': 'يرجى إعطاء تقييم عام',
    'review.errorSending': 'خطأ في إرسال التقييم',

    // Formula Selector
    'formula.title': 'اختر صيغتك',
    'formula.subtitle': 'حدد نوع الخدمة التي تناسبك',
    'formula.learnMore': 'معرفة المزيد',
    'formula.loading': 'جاري تحميل الصيغ...',
    'formula.standard': 'عادي',
    'formula.recurring': 'متكرر',
    'formula.premium': 'مميز',
    'formula.urgent': 'عاجل',
    'formula.night': 'ليلي',
    'formula.recommendedForTime': 'موصى به لهذا الوقت',
    'formula.suitedForUrgency': 'مناسب لحالتك العاجلة',
    'formula.specialRules': 'هذه الخدمة لها قواعد خاصة',

    // Login Page
    'login.title': 'تسجيل دخول العميل',
    'login.subtitle': 'الوصول إلى حسابك في GlamGo وحجز خدماتك',
    'login.backToHome': 'العودة للرئيسية',
    'login.emailRequired': 'البريد الإلكتروني مطلوب',
    'login.emailInvalid': 'البريد الإلكتروني غير صالح',
    'login.passwordRequired': 'كلمة المرور مطلوبة',
    'login.wrongCredentials': 'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    'login.forgotPassword': 'نسيت كلمة المرور؟',
    'login.rememberMe': 'تذكرني',
    'login.connecting': 'جاري تسجيل الدخول...',
    'login.connect': 'تسجيل الدخول',
    'login.noAccount': 'ليس لديك حساب؟',
    'login.signUp': 'سجّل الآن',
    'login.areProvider': 'أنت مقدم خدمة؟',
    'login.providerLogin': 'دخول مقدم الخدمة',
    'login.showPassword': 'إظهار كلمة المرور',
    'login.hidePassword': 'إخفاء كلمة المرور',

    // Register Page
    'register.personalInfo': 'المعلومات الشخصية',
    'register.yourAddress': 'عنوانك',
    'register.paymentMethod': 'طريقة الدفع',
    'register.yourPreferences': 'تفضيلاتك',
    'register.createAccount': 'أنشئ حسابك في GlamGo',
    'register.whereService': 'أين تريد استلام خدماتك؟',
    'register.registerCard': 'سجّل بطاقتك البنكية',
    'register.customizeExperience': 'خصّص تجربتك (اختياري)',
    'register.stepInfo': 'معلومات',
    'register.stepAddress': 'العنوان',
    'register.stepPayment': 'الدفع',
    'register.stepPreferences': 'التفضيلات',
    'register.firstNameRequired': 'الاسم الأول مطلوب',
    'register.lastNameRequired': 'اسم العائلة مطلوب',
    'register.phoneRequired': 'رقم الهاتف مطلوب',
    'register.phoneInvalid': 'يجب أن يبدأ الرقم بـ 06 أو 07 ويتكون من 10 أرقام',
    'register.birthDateRequired': 'تاريخ الميلاد مطلوب',
    'register.mustBe18': 'يجب أن يكون عمرك 18 سنة على الأقل للتسجيل',
    'register.passwordMinLength': 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل',
    'register.confirmPasswordRequired': 'يرجى تأكيد كلمة المرور',
    'register.passwordsDontMatch': 'كلمات المرور غير متطابقة',
    'register.acceptTerms': 'يجب قبول الشروط للمتابعة',
    'register.addressRequired': 'العنوان مطلوب',
    'register.selectAddressWithGeo': 'يرجى اختيار عنوان مع تحديد الموقع الجغرافي',
    'register.cityRequired': 'المدينة مطلوبة',
    'register.yourFirstName': 'اسمك الأول',
    'register.yourLastName': 'اسم عائلتك',
    'register.minimum6Chars': '6 أحرف كحد أدنى',
    'register.retypePassword': 'أعد كتابة كلمة المرور',
    'register.iAccept': 'أوافق على',
    'register.termsAndConditions': 'الشروط والأحكام',
    'register.and': 'و',
    'register.privacyPolicy': 'سياسة الخصوصية',
    'register.continue': 'متابعة',
    'register.back': 'رجوع',
    'register.registering': 'جاري التسجيل...',
    'register.successRegistration': 'تم التسجيل بنجاح! لنقم بإعداد طريقة الدفع.',
    'register.connectionError': 'خطأ في الاتصال. يرجى تسجيل الدخول يدوياً.',
    'register.cardSaved': 'تم حفظ البطاقة! الخطوة الأخيرة...',
    'register.selectServices': 'اختر الخدمات التي تهمك لتخصيص تجربتك.',
    'register.skip': 'تخطي',
    'register.finalizing': 'جاري الإنهاء...',
    'register.finish': 'إنهاء',
    'register.haveAccount': 'لديك حساب بالفعل؟',
    'register.logIn': 'سجّل الدخول',
    'register.completeAddress': 'العنوان الكامل',
    'register.startTypingAddress': 'ابدأ بكتابة عنوانك...',
    'register.selectSuggestedAddress': 'اختر عنواناً مقترحاً للحصول على موقع دقيق',
    'register.selectCity': 'اختر مدينتك',
    'register.paymentInfo': 'يمكنك أيضاً الدفع نقداً عند تقديم الخدمة. البطاقة البنكية تُستخدم كضمان لحجوزاتك.',

    // Profile Page
    'profile.title': 'ملفي الشخصي',
    'profile.subtitle': 'إدارة معلوماتك الشخصية',
    'profile.loading': 'جاري التحميل...',
    'profile.profilePhoto': 'صورة الملف الشخصي',
    'profile.change': 'تغيير',
    'profile.user': 'مستخدم',
    'profile.clientGlamgo': 'عميل GlamGo',
    'profile.modify': 'تعديل',
    'profile.firstName': 'الاسم الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.emailAddress': 'البريد الإلكتروني',
    'profile.phone': 'الهاتف',
    'profile.birthDate': 'تاريخ الميلاد',
    'profile.city': 'المدينة',
    'profile.selectCity': 'اختر مدينة',
    'profile.address': 'العنوان',
    'profile.typeAddress': 'اكتب عنوانك (مثال: المعاريف، جليز...)',
    'profile.saving': 'جاري الحفظ...',
    'profile.save': 'حفظ',
    'profile.updateSuccess': 'تم تحديث الملف الشخصي بنجاح!',
    'profile.updateError': 'خطأ في تحديث الملف الشخصي',
    'profile.imageTooBig': 'يجب ألا تتجاوز الصورة 5 ميغابايت',
    'profile.fileMustBeImage': 'يجب أن يكون الملف صورة',
    'profile.uploadError': 'خطأ في رفع الصورة',
    'profile.statistics': 'الإحصائيات',
    'profile.memberSince': 'عضو منذ {date}',
    'profile.security': 'الأمان',
    'profile.accountSecured': 'حسابك مؤمّن',
    'profile.loyalty': 'الولاء',
    'profile.premiumServices': 'استمتع بخدماتنا المميزة',

    // Cards
    'card.servicesAvailable': '{count} خدمات متاحة',
    'card.perService': '/ الخدمة',
    'card.from': 'ابتداءً من',
    'card.bookNow': 'احجز الآن',

    // Price Breakdown
    'price.calculating': 'جاري حساب السعر...',
    'price.calculationError': 'خطأ في الحساب',
    'price.connectionError': 'خطأ في الاتصال',
    'price.basePrice': 'السعر الأساسي',
    'price.distanceFee': 'رسوم التنقل',
    'price.noDistanceFee': 'بدون رسوم تنقل',
    'price.nightSupplement': 'رسوم إضافية ليلية',
    'price.nights': 'ليالي',
    'price.consecutiveNights': 'ليالي متتالية',
    'price.total': 'المجموع',
    'price.details': 'تفاصيل السعر',
    'price.formula': 'الصيغة',
    'price.duration': 'المدة',
    'price.quantity': 'الكمية',
    'price.totalDistance': 'المسافة الإجمالية',
    'price.freeRadius': 'النطاق المجاني',
    'price.excessDistance': 'المسافة الإضافية',
    'price.rate': 'التعريفة',
    'price.travel': 'التنقل',
    'price.included': 'مشمول',
    'price.subtotal': 'المجموع الفرعي',
    'price.commission': 'عمولة GlamGo',
    'price.totalToPay': 'المبلغ الإجمالي',
    'price.providerEarnings': 'إيرادات مقدم الخدمة',
    'price.nightService': 'خدمة ليلية (22:00 - 6:00)',

    // Distance Fee Modal
    'distance.title': 'رسوم التنقل',
    'distance.howCalculated': 'كيف يتم حساب الرسوم لـ {name}',
    'distance.footerNote': 'رسوم التنقل تسمح لمقدم الخدمة بتغطية تنقلاته خارج نطاق تدخله المعتاد.',
    'distance.understood': 'فهمت',
    'distance.provider': 'مقدم الخدمة',
    'distance.radius': 'النطاق',
    'distance.yourPosition': 'موقعك',
    'distance.distanceLabel': 'المسافة',
    'distance.totalDistance': 'المسافة الإجمالية',
    'distance.freeRadius': 'نطاق التدخل المجاني',
    'distance.excessDistance': 'المسافة الإضافية',
    'distance.none': 'لا شيء',
    'distance.free': 'مجاني',
    'distance.noFee': 'بدون رسوم تنقل',
    'distance.feeAmount': '+{amount} {currency} رسوم التنقل',
    'distance.freeZone': 'منطقة التدخل المجانية',
    'distance.inRadius': 'أنت على بعد {distance} كم من مقدم الخدمة، ضمن نطاق تدخله البالغ {radius} كم.',
    'distance.outOfRadius': 'أنت على بعد {distance} كم من مقدم الخدمة، خارج نطاق تدخله البالغ {radius} كم.',
    'distance.calculationDetail': 'تفاصيل الحساب',
    'distance.inRadiusInfo': 'مقدم الخدمة هذا يعمل في منطقتك بدون رسوم إضافية.',
    'distance.outOfRadiusInfo': 'هذه الرسوم تسمح لمقدم الخدمة بتغطية تنقلاته الإضافية للوصول إليك.',
    'distance.noFeeInZone': 'بدون رسوم تنقل - أنت في منطقة التدخل',
    'distance.alertExplanation': 'مقدم الخدمة هذا يعمل مجاناً حتى {radius} كم. عنوانك على بعد {distance} كم.',
    'distance.additionalDistance': 'المسافة الإضافية',
    'distance.rate': 'التعريفة',

    // Services Page
    'services.loading': 'جاري تحميل الخدمات...',
    'services.allServices': 'جميع خدماتنا',
    'services.subtitle': 'اكتشف مجموعتنا الواسعة من الخدمات المنزلية في مراكش',
    'services.discoverFormulas': 'اكتشف صيغ التسعير لدينا',
    'services.noServices': 'لا توجد خدمات متاحة',
    'services.filterByCategory': 'تصفية حسب الفئة',
    'services.allCategories': 'جميع الخدمات',
    'services.searchPlaceholder': 'البحث عن خدمة...',
    'services.radius': 'النطاق',
    'services.noResults': 'لم يتم العثور على خدمات',
    'services.noResultsHint': 'حاول تعديل معايير البحث',
    'services.resultsCount': '{count} خدمة',

    // Common
    'common.required': 'مطلوب',
    'common.optional': 'اختياري',
    'common.cancel': 'إلغاء',
    'common.error': 'خطأ',
    'common.close': 'إغلاق',
    'common.reviews': 'تقييمات',
    'common.loading': 'جاري التحميل...',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('fr');
  const [isRTL, setIsRTL] = useState(false);

  // Charger la langue sauvegardée
  useEffect(() => {
    const savedLanguage = localStorage.getItem('glamgo_language');
    if (savedLanguage && (savedLanguage === 'fr' || savedLanguage === 'ar')) {
      setLanguage(savedLanguage);
      setIsRTL(savedLanguage === 'ar');
    }
  }, []);

  // Appliquer la direction RTL
  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;

    // Ajouter/retirer la classe RTL pour le styling
    if (isRTL) {
      document.body.classList.add('rtl');
    } else {
      document.body.classList.remove('rtl');
    }
  }, [isRTL, language]);

  // Changer de langue
  const toggleLanguage = useCallback(() => {
    const newLang = language === 'fr' ? 'ar' : 'fr';
    setLanguage(newLang);
    setIsRTL(newLang === 'ar');
    localStorage.setItem('glamgo_language', newLang);
  }, [language]);

  // Fonction de traduction
  const t = useCallback((key, params = {}) => {
    let text = translations[language][key] || translations['fr'][key] || key;

    // Remplacer les paramètres {param}
    Object.keys(params).forEach(param => {
      text = text.replace(`{${param}}`, params[param]);
    });

    return text;
  }, [language]);

  return (
    <LanguageContext.Provider value={{
      language,
      setLanguage,
      toggleLanguage,
      t,
      isRTL,
      translations: translations[language]
    }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

export default LanguageContext;
